### PR TITLE
Update steps for slack.

### LINKED ISSUE #16: Add updated instructions for setting the colorscheme on slack.
First of all thank you for the beautiful theme. It works perfectly for me. 

I followed the instructions to add the colorscheme to slack, and the current steps to do that are a bit different as described in the README. 

I am opening this issue to discuss if you think it should be updated or not, and I will also create requests from my fork of the repo. 

I look forward for your feedback.

### PR DESCRIPTION
**Pull request by anubhavcodes**
Fixes #16

### CODE REVIEW

**Review by Rigellute — APPROVED** [review]
Thank you @anubhavcodes, this is great 👍

**Comment by anubhavcodes** [comment]
@Rigellute No worries, I am already thinking about migrating it to IntelliJ IDEs. The colours look beautiful on my terminal and VSCode. 

By the way, is it okay for you to label the PR as  **hacktoberfest-accepted** ? It's also fine if you don't. :) More details on why are [here](https://hacktoberfest.digitalocean.com/faq)

**Comment by Rigellute** [comment]
I added the `hacktoberfest` topic to the repo. Did that not pull through? I can add the label here too

**Comment by Rigellute** [comment]
Would be awesome to see the theme in intellij!

**Comment by anubhavcodes** [comment]
Yes that's correct, I didn't see it before. It's already counting toward the PRs in my hactoberfest dashboard, even without the label. 

Thanks again.

**Pull request merged**
